

version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: ${RESTART_POLICY}

  godbo_api:
    depends_on:
      - redis
    restart: ${RESTART_POLICY}
    build: .
    ports:
      - "8000:8076"
    environment:
      - API_ROOT_PATH
    links:
      - "redis:godbo_redis"